services:
  sidekiq:
    build: ./booking_control_service
    command: bundle exec sidekiq
    volumes:
      - ./booking_control_service:/app
    environment:
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq

  control_service:
    build: ./control_service
    volumes:
      - ./control_service:/app
    stdin_open: true
    tty: true
    ports:
      - "3003:3003"
    command: rails server -p 3003 -b 0.0.0.0
    depends_on:
      - cs_db

  cs_db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres1:/var/lib/postgresql/data

  ticket_service:
    build: ./ticket_service
    volumes:
      - ./ticket_service:/app
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
    command: rails server -p 3001 -b 0.0.0.0
    depends_on:
      - ts_db

  ts_db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres2:/var/lib/postgresql/data

  booking_control_services:
    build: ./booking_control_service
    volumes:
      - ./booking_control_service:/app
    command: ruby booking_control_service.rb
    stdin_open: true
    tty: true
    ports:
      - "3002:3002"
    depends_on:
      - sidekiq

volumes:
  postgres1:
  postgres2:
  rabbit:
  redis:
